name: Deploy Symfony

on:
  push:
    branches: [ master ]  # Déploiement à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql

#      - name: Check bundles.php
#        run: grep MakerBundle config/bundles.php || echo "MakerBundle OK"
#
#      - name: Clear & warmup Symfony cache
#        run: |
#          rm -rf var/cache/*
#          composer install --no-dev --optimize-autoloader --no-interaction
#          php bin/console cache:clear --env=prod
#          php bin/console cache:warmup --env=prod
#
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/cicd
            git pull origin master
            composer install --no-dev --optimize-autoloader --no-interaction
            php bin/console doctrine:schema:update --force
            php bin/console cache:clear
